import type { AssessmentRecord, BIDSScores } from '@/types/assessment';

/**
 * Generate CSV export of assessment scores for SPSS/R/Excel import.
 */
export function generateCSVExport(record: AssessmentRecord, scores: BIDSScores): string {
  const headers = [
    'assessment_id',
    'timestamp',
    'actual_bf',
    'actual_weight',
    'actual_bmi',
    'actual_waist',
    'actual_hip',
    'actual_whr',
    'perceived_global_bf',
    'ideal_global_bf',
    'partner_global_bf',
    'perceived_shoulders',
    'perceived_arms',
    'perceived_torso',
    'perceived_waist',
    'perceived_hips',
    'perceived_legs',
    'ideal_shoulders',
    'ideal_arms',
    'ideal_torso',
    'ideal_waist',
    'ideal_hips',
    'ideal_legs',
    'partner_shoulders',
    'partner_arms',
    'partner_torso',
    'partner_waist',
    'partner_hips',
    'partner_legs',
    'bids_distortion',
    'bids_dissatisfaction',
    'bids_partner_discrepancy',
    'distortion_magnitude',
    'dissatisfaction_magnitude',
    'max_distortion_segment',
    'max_dissatisfaction_segment',
    'perceived_duration_ms',
    'ideal_duration_ms',
    'partner_duration_ms',
    'total_duration_ms',
    'perceived_resets',
    'ideal_resets',
    'partner_resets',
    'clinical_flag',
  ];

  const p = record.tasks.perceived.finalState;
  const i = record.tasks.ideal.finalState;
  const pt = record.tasks.partner.finalState;

  const values = [
    record.id,
    record.timestamp,
    record.actual.bodyFat,
    record.actual.weight,
    record.actual.bmi,
    record.actual.waistCirc,
    record.actual.hipCirc,
    record.actual.whr,
    p.globalBodyFat,
    i.globalBodyFat,
    pt.globalBodyFat,
    p.segmentOverrides.shoulders,
    p.segmentOverrides.arms,
    p.segmentOverrides.torso,
    p.segmentOverrides.waist,
    p.segmentOverrides.hips,
    p.segmentOverrides.legs,
    i.segmentOverrides.shoulders,
    i.segmentOverrides.arms,
    i.segmentOverrides.torso,
    i.segmentOverrides.waist,
    i.segmentOverrides.hips,
    i.segmentOverrides.legs,
    pt.segmentOverrides.shoulders,
    pt.segmentOverrides.arms,
    pt.segmentOverrides.torso,
    pt.segmentOverrides.waist,
    pt.segmentOverrides.hips,
    pt.segmentOverrides.legs,
    scores.distortion,
    scores.dissatisfaction,
    scores.partnerDiscrepancy,
    scores.distortionMagnitude,
    scores.dissatisfactionMagnitude,
    scores.maxDistortionSegment,
    scores.maxDissatisfactionSegment,
    scores.perceivedTaskDuration,
    scores.idealTaskDuration,
    scores.partnerTaskDuration,
    scores.totalAssessmentDuration,
    record.tasks.perceived.resetCount,
    record.tasks.ideal.resetCount,
    record.tasks.partner.resetCount,
    scores.clinicalFlag ? 1 : 0,
  ];

  return headers.join(',') + '\n' + values.join(',') + '\n';
}
